/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as AdminHistorialAdelantosRouteImport } from './routes/admin.historial-adelantos'
import { Route as AdminEmpresasRouteImport } from './routes/admin.empresas'
import { Route as AdminControlPagosRouteImport } from './routes/admin.control-pagos'
import { Route as AdminConfiguracionRouteImport } from './routes/admin.configuracion'
import { Route as AdminAuditoriasRouteImport } from './routes/admin.auditorias'
import { Route as AdminAdelantosRouteImport } from './routes/admin.adelantos'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHistorialAdelantosRoute = AdminHistorialAdelantosRouteImport.update({
  id: '/historial-adelantos',
  path: '/historial-adelantos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmpresasRoute = AdminEmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminControlPagosRoute = AdminControlPagosRouteImport.update({
  id: '/control-pagos',
  path: '/control-pagos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracionRoute = AdminConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditoriasRoute = AdminAuditoriasRouteImport.update({
  id: '/auditorias',
  path: '/auditorias',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdelantosRoute = AdminAdelantosRouteImport.update({
  id: '/adelantos',
  path: '/adelantos',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/adelantos': typeof AdminAdelantosRoute
  '/admin/auditorias': typeof AdminAuditoriasRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/control-pagos': typeof AdminControlPagosRoute
  '/admin/empresas': typeof AdminEmpresasRoute
  '/admin/historial-adelantos': typeof AdminHistorialAdelantosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/adelantos': typeof AdminAdelantosRoute
  '/admin/auditorias': typeof AdminAuditoriasRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/control-pagos': typeof AdminControlPagosRoute
  '/admin/empresas': typeof AdminEmpresasRoute
  '/admin/historial-adelantos': typeof AdminHistorialAdelantosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/adelantos': typeof AdminAdelantosRoute
  '/admin/auditorias': typeof AdminAuditoriasRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/control-pagos': typeof AdminControlPagosRoute
  '/admin/empresas': typeof AdminEmpresasRoute
  '/admin/historial-adelantos': typeof AdminHistorialAdelantosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/admin/adelantos'
    | '/admin/auditorias'
    | '/admin/configuracion'
    | '/admin/control-pagos'
    | '/admin/empresas'
    | '/admin/historial-adelantos'
    | '/admin/usuarios'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/adelantos'
    | '/admin/auditorias'
    | '/admin/configuracion'
    | '/admin/control-pagos'
    | '/admin/empresas'
    | '/admin/historial-adelantos'
    | '/admin/usuarios'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/admin/adelantos'
    | '/admin/auditorias'
    | '/admin/configuracion'
    | '/admin/control-pagos'
    | '/admin/empresas'
    | '/admin/historial-adelantos'
    | '/admin/usuarios'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/historial-adelantos': {
      id: '/admin/historial-adelantos'
      path: '/historial-adelantos'
      fullPath: '/admin/historial-adelantos'
      preLoaderRoute: typeof AdminHistorialAdelantosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/empresas': {
      id: '/admin/empresas'
      path: '/empresas'
      fullPath: '/admin/empresas'
      preLoaderRoute: typeof AdminEmpresasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/control-pagos': {
      id: '/admin/control-pagos'
      path: '/control-pagos'
      fullPath: '/admin/control-pagos'
      preLoaderRoute: typeof AdminControlPagosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracion': {
      id: '/admin/configuracion'
      path: '/configuracion'
      fullPath: '/admin/configuracion'
      preLoaderRoute: typeof AdminConfiguracionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/auditorias': {
      id: '/admin/auditorias'
      path: '/auditorias'
      fullPath: '/admin/auditorias'
      preLoaderRoute: typeof AdminAuditoriasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/adelantos': {
      id: '/admin/adelantos'
      path: '/adelantos'
      fullPath: '/admin/adelantos'
      preLoaderRoute: typeof AdminAdelantosRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdelantosRoute: typeof AdminAdelantosRoute
  AdminAuditoriasRoute: typeof AdminAuditoriasRoute
  AdminConfiguracionRoute: typeof AdminConfiguracionRoute
  AdminControlPagosRoute: typeof AdminControlPagosRoute
  AdminEmpresasRoute: typeof AdminEmpresasRoute
  AdminHistorialAdelantosRoute: typeof AdminHistorialAdelantosRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdelantosRoute: AdminAdelantosRoute,
  AdminAuditoriasRoute: AdminAuditoriasRoute,
  AdminConfiguracionRoute: AdminConfiguracionRoute,
  AdminControlPagosRoute: AdminControlPagosRoute,
  AdminEmpresasRoute: AdminEmpresasRoute,
  AdminHistorialAdelantosRoute: AdminHistorialAdelantosRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
